# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4450f5ca5c8d85f734430d43e2beae4980950a7cdaa280fcd94dd519e76d3590377f5f88cdcfbc29b2c80040c2ff16dfac10aff0c290813d2c181b8aec38e18c

test:
  secret_key_base: 66b161693123c54edc45b5e4b583517885aaa55711104e0b21ff09cb82970e195d9ef4e3a6bcc960a770f4cd7834d851714a7379cefa4765cc82c25dfe1a5be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
